global using CommunityToolkit.Mvvm.ComponentModel;
global using Maui.Apps.Framework.Exceptions;
global using Maui.Apps.Framework.Extentions;
global using MonkeyCache;
global using System.Collections.ObjectModel;
global using System.Globalization;
global using System.Net.Http.Headers;
global using System.Text;
global using System.Text.Json;
